### ISSUE TITLE
[Question/Idea] Parsing JS objects (as in BrowserWindow constructor)

### ISSUE THREAD

**Issue by frankhale** [tht13/electrino#2]
One of the first things I wanted to do when I cloned your code was parse the object that was in the BrowserWindow constructor so that I could set the window width and height. The problem was that I couldn't figure out how to do it but did find a solution online after some time. 

I ended up adopting the solution that is talked about in this blog: https://www.microsoft.com/reallifecode/2016/06/02/hybrid-apps-using-c-and-javascript-with-chakracore/

Scroll down to Direct Object Model Conversion (With Json.NET) where it talks about how to and provides an example of converting a JS object to an object that can easily be used in C#. 

This works perfectly well and I was able to then parse the object passed to the BrowserWindow to set the preferred width and height of the window.

I guess my question is, before I submit a patch do you think this is a decent solution to the problem (eg. parsing JS objects so they can be consumed in C#) or is there a different way to do it that doesn't require taking on the dependency of Json.NET?

**Comment by frankhale** [comment]
If this is okay I'll submit a patch. I guess if need be it can be changed later if there is a better way to do it.

**Comment by tht13** [comment]
I'm fine with the implementation there, would be very useful :+1: 
You will include both to JSObject and from right?

**Comment by frankhale** [comment]
The implementation is pretty simple. I'll submit a patch soon for this.

**Comment by frankhale** [comment]
PR submitted for this: https://github.com/tht13/electrino/pull/4

**Comment by frankhale** [comment]
Just updated the patch and it now includes both helper classes, one to convert JavaScriptValue to JToken and JToken back to JavaScriptValue
