### ISSUE TITLE
[Idea] Setting titlebar text

### ISSUE THREAD

**Issue by frankhale** [tht13/electrino#3]
This sort of follows the last issue I posted about parsing the object passed in the BrowserWindow constructor. When I implemented the parsing in my own fork I wanted to set the title of the window except I didn't realize that the title is appended with the application display name that comes from the UWP manifest. I dug around on the internet and came to the conclusion that we'd need to have a custom titlebar to set the text the way we want it. I planned on working on this (or rather learning how to do it) so I wouldn't mind submitting a patch when I have something working.

**Comment by tht13** [comment]
I haven't looked at the window title bar yet, but I've seen that if we want to set the title for the installed program then the user would have to build this themselves as that is taken from the manifest. Some script trickery could also be used :wink:

**Comment by frankhale** [comment]
Basically the way I understood it from Googling is that you have to implement a custom titlebar and then just have an area on the titlebar where you set the text. This gets around the UWP app automatically setting it to the app display name in the manifest and then appending anything you try to set via calling the function to set the window title.

**Comment by frankhale** [comment]
I'm going to close this for now. Will reopen when I get around to making the custom titlebar.
